name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Rebuild native modules
        run: npx electron-rebuild

      - name: Build Electron app
        run: npm run build
        env:
          ELECTRON_BUILDER_BINARIES_MIRROR: https://npmmirror.com/mirrors/electron-builder-binaries/
          ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            dist/*.exe
            dist/*.yml
            dist/*.blockmap
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
